# Generated by Django 3.2.7 on 2021-12-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('inventario', models.IntegerField(verbose_name='Inventario')),
            ],
        ),
    ]
