# Generated by Django 3.2.7 on 2021-12-07 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='id',
            new_name='idProducts',
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('ctaVendidos', models.IntegerField(default=1, verbose_name='Productos vendidos')),
                ('idProducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idProduct', to='authApp.products')),
            ],
        ),
    ]
