# Generated by Django 3.2.7 on 2021-12-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_auto_20211207_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='idProducts',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='factura',
            name='ctaVendidos',
            field=models.IntegerField(default=1, verbose_name='Productos vendidos total'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
