# Generated by Django 3.2.7 on 2021-12-10 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_auto_20211209_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='valorTotal',
            field=models.IntegerField( verbose_name='Valor Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='ctaVendidos',
            field=models.IntegerField(default=1, verbose_name='Cantidad de Productos'),
        ),
    ]
