# Generated by Django 3.2.7 on 2021-12-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_auto_20211209_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='valorTotal',
        ),
    ]
