# Generated by Django 3.2.7 on 2021-12-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_remove_factura_valortotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='valorCompra',
            field=models.IntegerField(default=1, verbose_name='Valor Total de Compra'),
        ),
    ]
